name: PR Comment Workflow
on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check Events
        if: contains(github.event.issue.pull_request.html_url, '/pull/') && github.event.issue.state != 'closed'
        run: |
          echo "${{ github.event.comment.body }}"
