name: PR Comment Workflow
on:
  issue_comment:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'run_integration_tests')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Check out code
        run: |
          gh pr checkout ${{ github.event.issue.number }}
          # do your job...
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required for gh
