name: Unit Tests
run-name: Running unit tests 🚀
on: 
  pull_request:
    types: [opened, reopened]

permissions:
  id-token: write
  pull-requests: write
  issues: write
  checks: write 
  contents: write
  packages: read

jobs:
  RUN_TESTS:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Install xmlstarlet
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet
    
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      
      - name: Generate Go Tests
        continue-on-error: true
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          go test -v -race -cover -covermode=atomic -json 2>&1 ./... -coverprofile=cover.out | go-junit-report -parser gojson > ./report.xml
          
          total=$(xmlstarlet sel -t -v "count(//testcase)" ./report.xml)
          # Get the number of test cases failed
          failed=$(xmlstarlet sel -t -v "count(//testcase[failure])" ./report.xml)
          
          echo "PASSED=$passed">> $GITHUB_ENV
          echo "TOTAL=$total">> $GITHUB_ENV

      - name: Upload comment
        run: |
          dummy_url="https://abcdefkjnadkjsnkdnsakjdn.com/sdkjnajkdnkjsandjkansd"
          COMMENT="🚀 TEST REPORT: $dummy_url  \nNumber of test cases passed: ${{ env.PASSED }}  \nNumber of test cases failed: ${{ env.FAILED }}"
          API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          AUTH_HEADER="Authorization: Bearer ${{ env.GITHUB_BOT_PAC }}"
          
          # curl -X POST -H "Content-Type: application/json" -H "$AUTH_HEADER" -d "{\"body\":\"$COMMENT\"}" $API_URL
          BODY=$(echo "$COMMENT" | jq -Rs '{"body": .}')
          echo $BODY
          curl -X POST -H "Content-Type: application/json" -H "$AUTH_HEADER" -d "$BODY" $API_URL
          
      # - name: Upload coverage reports to Codecov
      #   run: |
      #      curl -Os https://uploader.codecov.io/latest/linux/codecov
      #      chmod +x codecov
      #      ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f ./cover.out -F "integrationtest"

      # - name: Add comment to PR Again
      #   run: |
      #     COMMENT="🚀 Check Unit Test Coverage: https://app.codecov.io/github/${{github.repository}}"
      #     API_URL="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
      #     AUTH_HEADER="Authorization: Bearer ${{ env.GITHUB_BOT_PAC }}"
          
      #     curl -X POST -H "Content-Type: application/json" -H "$AUTH_HEADER" -d "{\"body\":\"$COMMENT\"}" $API_URL
